### PR TITLE
a summary function for QVDLoaders/creators

### PR DESCRIPTION
**Pull request by HectorMunoz**
Hi, I did this SUB time ago. To me is very helpful to see what qvd's are created and what was their last update, even their size.

I've uploaded the script and the example.

Hope this helps.

Best Regards

Ps. I'm very new to this github system, so I hope did the process the right way.

### CODE REVIEW

**Comment by RobWunderlich** [comment]
So the intent is to call this routine after each STORE to create stats for the QVD just created?

**Comment by HectorMunoz** [comment]
In fact, the routine also creates the QVD (given or not the filename), drop it from memory and also creates stats about, records, size and reload time involve.

in example you can replace this statements:

```
store table1 into table1.qvd (qvd);
drop table table1;
```

by

`CALL Qvc_LoadStats('table1');`

and the qvw will maintain the stats of the last reload.

**Comment by HectorMunoz** [comment]
image

an example of the routine result (also in the "Examples" folder)

**Comment by RobWunderlich** [comment]
Apologies for the delayed decision.  This update is good, but too broad for the mission of QVC.

**Pull request closed without merging**
